from five import grok
from zope import schema

from zope.component import getMultiAdapter
from zope.lifecycleevent import modified
from zope.interface import alsoProvides
from plone.directives import form

from plone.app.textfield import RichText
from plone.namedfile.field import NamedBlobImage
from plone.autoform.interfaces import IFormFieldProvider
from Products.statusmessages.interfaces import IStatusMessage

from ade25.panelpage.panelpage import IPanelPage

from ade25.panelpage import MessageFactory as _


class IPanelContent(form.Schema):
    """ Behavior storing panel content """

    # Hide behavior fields in autogenerated add and edit forms
    #form.omitted('textline', 'textblock', 'text', 'image')

    textline = schema.TextLine(
        title=_("Headline"),
        required=False,
    )
    textblock = schema.Text(
        title=_(u"Abstract"),
        required=False,
    )
    text = RichText(
        title=_(u"Body Text"),
        description=_(u"Please enter rich formatted text. But keep it short "
                      u"and suitable for a content panel"),
        required=False,
    )
    image = NamedBlobImage(
        title=_(u"Panel Icon Image"),
        description=_(u"Upload panel icon image suitable in size and "
                      u"dimension for the usecase"),
        required=False,
    )

alsoProvides(IPanelContent, IFormFieldProvider)
